### ISSUE TITLE
I can't load the assets resources and the mod doesn't work,How can I do?

### ISSUE THREAD

**Issue by ToDreamr** [Rist8/MiSide-UniversalAssetLoader#13]
![image](https://github.com/user-attachments/assets/1d3bd677-cfb8-418b-95bf-10505e33f300)

Like this:
![image](https://github.com/user-attachments/assets/cad9576a-da68-4a9b-b9c6-cb2a726c39de)

And I  don't konw the exception below:
![image](https://github.com/user-attachments/assets/681ad1bd-8518-4746-9cef-0aa9f05cfa4f)

Here is my plugins folder:
![image](https://github.com/user-attachments/assets/bf84bb5a-2734-4ae5-9447-ba7fc635f23e)

**Comment by Hazuki-san** [comment]
Move assimp.dll to main directory. (Along with MiSideFull or GameAssembly.dll)
