### ISSUE TITLE
Can I replace Unity Texture2D files with it?

### ISSUE THREAD

**Issue by crexlight** [Rist8/MiSide-UniversalAssetLoader#16]

**Comment by Rist8** [comment]
The replace_tex command in addons_config.txt allows you to replace the Unity Texture of the object's material described by the arguments with a Text2D texture created from the image file specified as one of the arguments to this command.

**Comment by vos6434** [comment]
Could you provide an example of Text2D texture replacement please?

**Comment by Rist8** [comment]
In cat ears addon there is an example of replacement, the null texture of newly created object CatEars is replced with CatEar_BaseColor texture

**Comment by vos6434** [comment]
Can I replace the games menu textures instead of character model textures?

**Comment by Rist8** [comment]
> Can I replace the games menu textures instead of character model textures?
Right now you can change only menu's logo and music using assets_config.txt. Other textures replacement is not supported by this mod yet.
