### ISSUE TITLE
"/" not work on version 0.91 with UniversalAssetLoader 0.9.5

### ISSUE THREAD

**Issue by tooyangtoonaive** [Rist8/MiSide-UniversalAssetLoader#17]
"/" not work on version 0.91 with UniversalAssetLoader 0.9.5

**Comment by Rist8** [comment]
It was removed because photo mode was added to the game, you can still use free camera by typing camerafly in console OR download console unlocker mod and change the bind for the pause as it's the only conflicting bind at the moment.

**Comment by Rist8** [comment]
Updated readme with this information
