### ISSUE TITLE
Default Model Error (CatEars)

### ISSUE THREAD

**Issue by Shark-vil** [Rist8/MiSide-UniversalAssetLoader#20]
```
[Error  :     Unity] [ERROR] Error while processing command: replace_mesh Mita CatEars CatEars\MitaCatMaid CatEars
System.Collections.Generic.KeyNotFoundException: The given key 'CatEars\MitaCatMaid' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Plugin.PatchMita(GameObject mita, Boolean recursive)
```
But directory and file exists:
![explorer_Uoft2HgA2P](https://github.com/user-attachments/assets/2bf6b3f5-4f90-4ac1-87f9-5bcb86ab65af)

**Comment by Hazuki-san** [comment]
Is `assimp.dll` inside game directory?

**Comment by Shark-vil** [comment]
> Is `assimp.dll` inside game directory?

Only loader plugin
![explorer_yuXniJccqV](https://github.com/user-attachments/assets/059d6fd9-cad8-4d04-a018-386fc86ae3bb)

**Comment by Shark-vil** [comment]
Okay, I'm stupid. Sorry.
