### ISSUE TITLE
nothing shows up in addons

### ISSUE THREAD

**Issue by waflers-himself** [Rist8/MiSide-UniversalAssetLoader#4]
ive followed the instal instructions and tried 2 times in diff directorys but every time i get everything to work so addons show up in clothes but nothing acctualy shows up in there. i linked a ss 
![image_2024-12-18_222721134](https://github.com/user-attachments/assets/0b1c45fe-4285-4365-81d5-b56911cca74b)

**Comment by waflers-himself** [comment]
i have stuff in the folders heres the logs

[LogOutput.log](https://github.com/user-attachments/files/18202252/LogOutput.log)
[ErrorLog.log](https://github.com/user-attachments/files/18202255/ErrorLog.log)

**Comment by Rist8** [comment]
C:\Users\Eduard\Downloads\MiSide-GoldBerg2\MiSide-GoldBerg\BepInEx\plugins\UniversalAssetLoader\Assets
send a screenshot of that directory

**Comment by waflers-himself** [comment]
![image](https://github.com/user-attachments/assets/6726bc6d-1570-4548-a67b-8e7abc10b1fb)

**Comment by waflers-himself** [comment]
![image](https://github.com/user-attachments/assets/535b8088-3d5f-4596-a326-f5ec89484362)

**Comment by Rist8** [comment]
Are you that's the contents of exactly that directory and there are no mistakes in any part of the path?

**Comment by waflers-himself** [comment]
yes

**Comment by waflers-himself** [comment]
could there be a chance its not working cas im using a pirated version?

**Comment by Rist8** [comment]
it's possible

**Comment by waflers-himself** [comment]
im prety sure its downloaded properly

**Comment by Rist8** [comment]
okay paste the screenshot of plugins folder at last

**Comment by waflers-himself** [comment]
i did

the ones up there

**Comment by Rist8** [comment]
you didn't send the plugins folder ss

**Comment by Rist8** [comment]
or is your Assets folder right in plugins folder?

**Comment by waflers-himself** [comment]
![image](https://github.com/user-attachments/assets/70ddece1-3474-4142-a13a-efbc5795192a)

**Comment by waflers-himself** [comment]
![image](https://github.com/user-attachments/assets/18d74f4e-f5cf-4a79-9baa-042bab7682f0)

**Comment by waflers-himself** [comment]
so is it a problem im the folders cas i followed the instructions ?

**Comment by Rist8** [comment]
It just wasn't the best style of instructon for plugin instalation
now it's a little bit more understandable
