### ISSUE TITLE
Batch file not working.

### ISSUE THREAD

**Issue by 3ylez** [Rist8/MiSide-UniversalAssetLoader#7]
After putting the batch in the OuterFolder which located in BeplnEx/plugins, it tells me this:
![Screenshot 2024-12-19 152409](https://github.com/user-attachments/assets/0c146c99-0f94-4b3f-b54b-e753d6795b97)
I tried turning off all firewalls, cause it said something about networking, I'm no big brainer, so I don't know anymore detailed. Just wanna know if it's a problem with my PC or the batch.

I did find a manual fix, by looking in the console, and figuring where the UAL is supposed to be.

**Comment by Rist8** [comment]
You probably have something weird happening with your STEAM_PATH variable, so it couldn't find the file which stores the directories for all steam libraries and the part for copying the files got \\= instead of the MiSide path

**Comment by Rist8** [comment]
Updated the move.bat file so that it tries to find the SteamPath from the alternative regestry key, please try to run the new version to know, whether it fixes the issue.

**Comment by 3ylez** [comment]
> Updated the move.bat file so that it tries to find the SteamPath from the alternative registry key, please try to run the new version to know, whether it fixes the issue.

Sadly it didn't fix the issue for me, but the window showed up and dissapeared saying: 
![image](https://github.com/user-attachments/assets/0eeb5f7e-1ae7-4e1c-accb-dc5a64054450)

I suppose something may be wrong with my steam, or idk, not a professional here.

**Comment by Rist8** [comment]
Alright i added 2 more possible SteamPath locations, can you try once more please?

**Comment by 3ylez** [comment]
> Allright i added 2 more possible SteamPath locations, can you try once more please?

Might be, that my steam thingy is corrupt, or something, I could re-install it later, it said the same thing.
If no one else has this problem, then it should be fine.

Or... I can re-intall steam on my laptop, and check how it works there.

**Comment by Rist8** [comment]
You don't have to, if you want you can help me with checking some of the entries in your registry and i'll try to solve this problem.
You can contact me in discord, i'm Rist/rist8

**Comment by Rist8** [comment]
Updated the move.bat so that it resolves the issue
