### ISSUE TITLE
assets not showing up

### ISSUE THREAD

**Issue by spi3z** [Rist8/MiSide-UniversalAssetLoader#8]
I downloaded everything like I should've but the addons aren't showing up and there's some kind of error in the console
![Screenshot 2024-12-19 183956](https://github.com/user-attachments/assets/38fca128-e245-4ba6-bc58-4b641cf8de3b)
![Screenshot 2024-12-19 184348](https://github.com/user-attachments/assets/15f64843-687c-447e-8d93-978de907137c)

**Comment by Rist8** [comment]
You extracted the plugin with the OuterFolder in it

**Comment by Rist8** [comment]
Just move the "UniversalAssetLoader" folder one directory up
