### ISSUE TITLE
how to move between locations

### ISSUE THREAD

**Issue by olegtraktor** [Rist8/MiSide-UniversalAssetLoader#9]
I use the levelload command and enter the location name but nothing happens. How do I do this correctly and is there a list of all the game locations?

**Comment by olegtraktor** [comment]
or what command to use to get the save of a completed game

**Comment by Rist8** [comment]
This mod's main focus is assets loading, so handling game-specific commands like levelload or fetching completed game saves isn't its core purpose. However, i can tell you that the levelload command probably isn't working correctly in the release version of the game and that you can't get a completed save using console.
